# Site settings
title: Forking Recipes
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Fancy getting to know some more about Forking Recipes? Then you've come to the right spot!"
baseurl: ""
url: "blog.forkingrecipes.com"
twitter_username: forkingrecipes
facebook_username:  forkingrecipes

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
